spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pindah
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081
